sudo: required
services:
  - docker

before_install:
  - docker build -t sharadjain21/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sharadjain21/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env:  "Dockerreact-env-1"
  bucket_name:  "elasticbeanstalk-us-east-2-891176831766"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY